//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ent_Semana3.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LN_DBEntities1 : DbContext
    {
        public LN_DBEntities1()
            : base("name=Quiz1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_TIPOCAMBIO> T_TIPOCAMBIO { get; set; }
    
        public virtual int InsertTipoCambio(string datos, Nullable<int> indicador)
        {
            var datosParameter = datos != null ?
                new ObjectParameter("Datos", datos) :
                new ObjectParameter("Datos", typeof(string));
    
            var indicadorParameter = indicador.HasValue ?
                new ObjectParameter("Indicador", indicador) :
                new ObjectParameter("Indicador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTipoCambio", datosParameter, indicadorParameter);
        }
    }
}
